# Generated by Django 4.2.1 on 2023-05-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_company_profile_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created', '-updated']},
        ),
        migrations.AddField(
            model_name='room',
            name='class_img',
            field=models.ImageField(default='group_icon.png', null=True, upload_to='class_img'),
        ),
    ]
