# Generated by Django 4.2.1 on 2023-05-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_message_options_room_class_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='class_img',
            field=models.ImageField(default='group_icon.png', upload_to='class_img'),
        ),
    ]
